/**
 * Delivery helpers for the bundled local photo archive.
 *
 * Local photos use publicIds of the form `local/<id>` and are served from
 * /photos/<id>/w<width>.webp, generated by scripts/build-photo-assets.mjs.
 * Cloudinary-hosted photos keep flowing through lib/image-policy.
 */
import { getManifestEntry, localPhotoId } from '@/content/worlds'
import type { ManifestEntry } from '@/content/worlds'

export interface LocalPhotoAsset {
  id: string
  width: number
  height: number
  aspectRatio: number
  palette: string[]
  placeholder: string
  src: string
  srcSet: string
}

function variantUrl(id: string, width: number) {
  return `/photos/${encodeURIComponent(id)}/w${width}.webp`
}

function toAsset(id: string, entry: ManifestEntry): LocalPhotoAsset | null {
  if (entry.hidden || entry.widths.length === 0) {
    return null
  }

  const widths = [...entry.widths].sort((a, b) => a - b)

  return {
    id,
    width: entry.width,
    height: entry.height,
    aspectRatio: entry.width / entry.height,
    palette: entry.palette,
    placeholder: entry.placeholder,
    src: variantUrl(id, widths.at(-1)!),
    srcSet: widths.map((width) => `${variantUrl(id, width)} ${width}w`).join(', '),
  }
}

/**
 * URL of the smallest local variant at or above `preferredWidth` (falls back
 * to the largest). Used by the WebGL layer to load texture-sized files
 * instead of full-resolution variants.
 */
export function getLocalVariantUrl(publicId: string, preferredWidth: number): string | null {
  const id = localPhotoId(publicId)
  const entry = id ? getManifestEntry(id) : null

  if (!id || !entry || entry.hidden || entry.widths.length === 0) {
    return null
  }

  const widths = [...entry.widths].sort((a, b) => a - b)
  const width = widths.find((value) => value >= preferredWidth) ?? widths.at(-1)!
  return variantUrl(id, width)
}

/** Returns delivery data for a local publicId, or null for Cloudinary/hidden photos. */
export function getLocalPhotoAsset(publicId: string): LocalPhotoAsset | null {
  const id = localPhotoId(publicId)

  if (!id) {
    return null
  }

  const entry = getManifestEntry(id)

  if (!entry) {
    return null
  }

  return toAsset(id, entry)
}
