/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Cta = {
  _type: "cta";
  label?: string;
  href?: string;
};

export type SocialLink = {
  _type: "socialLink";
  label?: string;
  href?: string;
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  imagePublicId?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type WorldReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "world";
};

export type Photo = {
  _id: string;
  _type: "photo";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  slug?: Slug;
  title?: string;
  alt?: string;
  description?: string;
  caption?: string;
  archived?: boolean;
  worldRef?: WorldReference;
  world?: string;
  series?: string;
  locationLabel?: string;
  tags?: Array<string>;
  captureDate?: string;
  camera?: string;
  lens?: string;
  focalLength?: string;
  iso?: string;
  shutterSpeed?: string;
  aperture?: string;
  sortOrder?: number;
};

export type PhotoReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "photo";
};

export type World = {
  _id: string;
  _type: "world";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  line?: string;
  description?: string;
  heroPhoto?: PhotoReference;
  status?: "active" | "hidden";
  sortOrder?: number;
  mood?: {
    wash?: string;
    deep?: string;
    accent?: string;
  };
  seo?: Seo;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type ContactPage = {
  _id: string;
  _type: "contactPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  headline?: string;
  body?: Array<string>;
  email?: string;
  socials?: Array<{
    _key: string;
  } & SocialLink>;
  seo?: Seo;
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  headline?: string;
  body?: Array<string>;
  photoHighlights?: Array<{
    _key: string;
  } & PhotoReference>;
  seo?: Seo;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  eyebrow?: string;
  headline?: string;
  intro?: string;
  featuredPhotos?: Array<{
    _key: string;
  } & PhotoReference>;
  cta?: Cta;
  seo?: Seo;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  brandMark?: string;
  title?: string;
  description?: string;
  location?: string;
  email?: string;
  socials?: Array<{
    _key: string;
  } & SocialLink>;
  seo?: Seo;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = Cta | SocialLink | Seo | SanityImageAssetReference | WorldReference | Photo | PhotoReference | World | Slug | SanityImageCrop | SanityImageHotspot | ContactPage | AboutPage | HomePage | SiteSettings | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;

// Source: ../web/src/server/providers/sanity.ts
// Variable: siteSettingsQuery
// Query: *[_type == "siteSettings"][0]{  brandMark,  title,  description,  location,  email,  socials[]{    label,    href  },  seo{    title,    description,    imagePublicId  }}
export type SiteSettingsQueryResult = {
  brandMark: string | null;
  title: string | null;
  description: string | null;
  location: string | null;
  email: string | null;
  socials: Array<{
    label: string | null;
    href: string | null;
  }> | null;
  seo: {
    title: string | null;
    description: string | null;
    imagePublicId: string | null;
  } | null;
} | null;

// Source: ../web/src/server/providers/sanity.ts
// Variable: homePageQuery
// Query: *[_type == "homePage"][0]{  eyebrow,  headline,  intro,  cta{    label,    href  },  featuredPhotos[]->{    "slug": slug.current  },  seo{    title,    description,    imagePublicId  }}
export type HomePageQueryResult = {
  eyebrow: string | null;
  headline: string | null;
  intro: string | null;
  cta: {
    label: string | null;
    href: string | null;
  } | null;
  featuredPhotos: Array<{
    slug: string | null;
  }> | null;
  seo: {
    title: string | null;
    description: string | null;
    imagePublicId: string | null;
  } | null;
} | null;

// Source: ../web/src/server/providers/sanity.ts
// Variable: aboutPageQuery
// Query: *[_type == "aboutPage"][0]{  headline,  body,  photoHighlights[]->{    "slug": slug.current  },  seo{    title,    description,    imagePublicId  }}
export type AboutPageQueryResult = {
  headline: string | null;
  body: Array<string> | null;
  photoHighlights: Array<{
    slug: string | null;
  }> | null;
  seo: {
    title: string | null;
    description: string | null;
    imagePublicId: string | null;
  } | null;
} | null;

// Source: ../web/src/server/providers/sanity.ts
// Variable: contactPageQuery
// Query: *[_type == "contactPage"][0]{  headline,  body,  email,  socials[]{    label,    href  },  seo{    title,    description,    imagePublicId  }}
export type ContactPageQueryResult = {
  headline: string | null;
  body: Array<string> | null;
  email: string | null;
  socials: Array<{
    label: string | null;
    href: string | null;
  }> | null;
  seo: {
    title: string | null;
    description: string | null;
    imagePublicId: string | null;
  } | null;
} | null;

// Source: ../web/src/server/providers/sanity.ts
// Variable: worldsQuery
// Query: *[_type == "world"] | order(sortOrder asc, name asc){  "slug": slug.current,  name,  line,  description,  sortOrder,  status,  heroPhoto->{    "slug": slug.current  },  mood{    wash,    deep,    accent  },  seo{    title,    description,    imagePublicId  }}
export type WorldsQueryResult = Array<{
  slug: string | null;
  name: string | null;
  line: string | null;
  description: string | null;
  sortOrder: number | null;
  status: "active" | "hidden" | null;
  heroPhoto: {
    slug: string | null;
  } | null;
  mood: {
    wash: string | null;
    deep: string | null;
    accent: string | null;
  } | null;
  seo: {
    title: string | null;
    description: string | null;
    imagePublicId: string | null;
  } | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[_type == \"siteSettings\"][0]{\n  brandMark,\n  title,\n  description,\n  location,\n  email,\n  socials[]{\n    label,\n    href\n  },\n  seo{\n    title,\n    description,\n    imagePublicId\n  }\n}": SiteSettingsQueryResult;
    "*[_type == \"homePage\"][0]{\n  eyebrow,\n  headline,\n  intro,\n  cta{\n    label,\n    href\n  },\n  featuredPhotos[]->{\n    \"slug\": slug.current\n  },\n  seo{\n    title,\n    description,\n    imagePublicId\n  }\n}": HomePageQueryResult;
    "*[_type == \"aboutPage\"][0]{\n  headline,\n  body,\n  photoHighlights[]->{\n    \"slug\": slug.current\n  },\n  seo{\n    title,\n    description,\n    imagePublicId\n  }\n}": AboutPageQueryResult;
    "*[_type == \"contactPage\"][0]{\n  headline,\n  body,\n  email,\n  socials[]{\n    label,\n    href\n  },\n  seo{\n    title,\n    description,\n    imagePublicId\n  }\n}": ContactPageQueryResult;
    "*[_type == \"world\"] | order(sortOrder asc, name asc){\n  \"slug\": slug.current,\n  name,\n  line,\n  description,\n  sortOrder,\n  status,\n  heroPhoto->{\n    \"slug\": slug.current\n  },\n  mood{\n    wash,\n    deep,\n    accent\n  },\n  seo{\n    title,\n    description,\n    imagePublicId\n  }\n}": WorldsQueryResult;
  }
}
