/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignalRouteImport } from './routes/signal'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorldsWorldRouteImport } from './routes/worlds.$world'
import { Route as PhotosSlugRouteImport } from './routes/photos.$slug'
import { Route as ApiWebhooksSanityRouteImport } from './routes/api/webhooks/sanity'
import { Route as ApiWebhooksCloudinaryRouteImport } from './routes/api/webhooks/cloudinary'
import { Route as ApiReconcileContentRouteImport } from './routes/api/reconcile/content'

const SignalRoute = SignalRouteImport.update({
  id: '/signal',
  path: '/signal',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldsWorldRoute = WorldsWorldRouteImport.update({
  id: '/worlds/$world',
  path: '/worlds/$world',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosSlugRoute = PhotosSlugRouteImport.update({
  id: '/photos/$slug',
  path: '/photos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksSanityRoute = ApiWebhooksSanityRouteImport.update({
  id: '/api/webhooks/sanity',
  path: '/api/webhooks/sanity',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksCloudinaryRoute = ApiWebhooksCloudinaryRouteImport.update({
  id: '/api/webhooks/cloudinary',
  path: '/api/webhooks/cloudinary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReconcileContentRoute = ApiReconcileContentRouteImport.update({
  id: '/api/reconcile/content',
  path: '/api/reconcile/content',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/archive': typeof ArchiveRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/notes': typeof NotesRoute
  '/signal': typeof SignalRoute
  '/photos/$slug': typeof PhotosSlugRoute
  '/worlds/$world': typeof WorldsWorldRoute
  '/api/reconcile/content': typeof ApiReconcileContentRoute
  '/api/webhooks/cloudinary': typeof ApiWebhooksCloudinaryRoute
  '/api/webhooks/sanity': typeof ApiWebhooksSanityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/archive': typeof ArchiveRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/notes': typeof NotesRoute
  '/signal': typeof SignalRoute
  '/photos/$slug': typeof PhotosSlugRoute
  '/worlds/$world': typeof WorldsWorldRoute
  '/api/reconcile/content': typeof ApiReconcileContentRoute
  '/api/webhooks/cloudinary': typeof ApiWebhooksCloudinaryRoute
  '/api/webhooks/sanity': typeof ApiWebhooksSanityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/archive': typeof ArchiveRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/notes': typeof NotesRoute
  '/signal': typeof SignalRoute
  '/photos/$slug': typeof PhotosSlugRoute
  '/worlds/$world': typeof WorldsWorldRoute
  '/api/reconcile/content': typeof ApiReconcileContentRoute
  '/api/webhooks/cloudinary': typeof ApiWebhooksCloudinaryRoute
  '/api/webhooks/sanity': typeof ApiWebhooksSanityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/archive'
    | '/contact'
    | '/gallery'
    | '/notes'
    | '/signal'
    | '/photos/$slug'
    | '/worlds/$world'
    | '/api/reconcile/content'
    | '/api/webhooks/cloudinary'
    | '/api/webhooks/sanity'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/archive'
    | '/contact'
    | '/gallery'
    | '/notes'
    | '/signal'
    | '/photos/$slug'
    | '/worlds/$world'
    | '/api/reconcile/content'
    | '/api/webhooks/cloudinary'
    | '/api/webhooks/sanity'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/archive'
    | '/contact'
    | '/gallery'
    | '/notes'
    | '/signal'
    | '/photos/$slug'
    | '/worlds/$world'
    | '/api/reconcile/content'
    | '/api/webhooks/cloudinary'
    | '/api/webhooks/sanity'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ArchiveRoute: typeof ArchiveRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  NotesRoute: typeof NotesRoute
  SignalRoute: typeof SignalRoute
  PhotosSlugRoute: typeof PhotosSlugRoute
  WorldsWorldRoute: typeof WorldsWorldRoute
  ApiReconcileContentRoute: typeof ApiReconcileContentRoute
  ApiWebhooksCloudinaryRoute: typeof ApiWebhooksCloudinaryRoute
  ApiWebhooksSanityRoute: typeof ApiWebhooksSanityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signal': {
      id: '/signal'
      path: '/signal'
      fullPath: '/signal'
      preLoaderRoute: typeof SignalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worlds/$world': {
      id: '/worlds/$world'
      path: '/worlds/$world'
      fullPath: '/worlds/$world'
      preLoaderRoute: typeof WorldsWorldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos/$slug': {
      id: '/photos/$slug'
      path: '/photos/$slug'
      fullPath: '/photos/$slug'
      preLoaderRoute: typeof PhotosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/sanity': {
      id: '/api/webhooks/sanity'
      path: '/api/webhooks/sanity'
      fullPath: '/api/webhooks/sanity'
      preLoaderRoute: typeof ApiWebhooksSanityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/cloudinary': {
      id: '/api/webhooks/cloudinary'
      path: '/api/webhooks/cloudinary'
      fullPath: '/api/webhooks/cloudinary'
      preLoaderRoute: typeof ApiWebhooksCloudinaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reconcile/content': {
      id: '/api/reconcile/content'
      path: '/api/reconcile/content'
      fullPath: '/api/reconcile/content'
      preLoaderRoute: typeof ApiReconcileContentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ArchiveRoute: ArchiveRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  NotesRoute: NotesRoute,
  SignalRoute: SignalRoute,
  PhotosSlugRoute: PhotosSlugRoute,
  WorldsWorldRoute: WorldsWorldRoute,
  ApiReconcileContentRoute: ApiReconcileContentRoute,
  ApiWebhooksCloudinaryRoute: ApiWebhooksCloudinaryRoute,
  ApiWebhooksSanityRoute: ApiWebhooksSanityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
