/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PhotosSlugRouteImport } from './routes/photos.$slug'
import { Route as ApiWebhooksSanityRouteImport } from './routes/api/webhooks/sanity'
import { Route as ApiWebhooksCloudinaryRouteImport } from './routes/api/webhooks/cloudinary'
import { Route as ApiReconcileContentRouteImport } from './routes/api/reconcile/content'

const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosSlugRoute = PhotosSlugRouteImport.update({
  id: '/photos/$slug',
  path: '/photos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksSanityRoute = ApiWebhooksSanityRouteImport.update({
  id: '/api/webhooks/sanity',
  path: '/api/webhooks/sanity',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksCloudinaryRoute = ApiWebhooksCloudinaryRouteImport.update({
  id: '/api/webhooks/cloudinary',
  path: '/api/webhooks/cloudinary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReconcileContentRoute = ApiReconcileContentRouteImport.update({
  id: '/api/reconcile/content',
  path: '/api/reconcile/content',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/photos/$slug': typeof PhotosSlugRoute
  '/api/reconcile/content': typeof ApiReconcileContentRoute
  '/api/webhooks/cloudinary': typeof ApiWebhooksCloudinaryRoute
  '/api/webhooks/sanity': typeof ApiWebhooksSanityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/photos/$slug': typeof PhotosSlugRoute
  '/api/reconcile/content': typeof ApiReconcileContentRoute
  '/api/webhooks/cloudinary': typeof ApiWebhooksCloudinaryRoute
  '/api/webhooks/sanity': typeof ApiWebhooksSanityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/photos/$slug': typeof PhotosSlugRoute
  '/api/reconcile/content': typeof ApiReconcileContentRoute
  '/api/webhooks/cloudinary': typeof ApiWebhooksCloudinaryRoute
  '/api/webhooks/sanity': typeof ApiWebhooksSanityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/photos/$slug'
    | '/api/reconcile/content'
    | '/api/webhooks/cloudinary'
    | '/api/webhooks/sanity'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/photos/$slug'
    | '/api/reconcile/content'
    | '/api/webhooks/cloudinary'
    | '/api/webhooks/sanity'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/photos/$slug'
    | '/api/reconcile/content'
    | '/api/webhooks/cloudinary'
    | '/api/webhooks/sanity'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  PhotosSlugRoute: typeof PhotosSlugRoute
  ApiReconcileContentRoute: typeof ApiReconcileContentRoute
  ApiWebhooksCloudinaryRoute: typeof ApiWebhooksCloudinaryRoute
  ApiWebhooksSanityRoute: typeof ApiWebhooksSanityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos/$slug': {
      id: '/photos/$slug'
      path: '/photos/$slug'
      fullPath: '/photos/$slug'
      preLoaderRoute: typeof PhotosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/sanity': {
      id: '/api/webhooks/sanity'
      path: '/api/webhooks/sanity'
      fullPath: '/api/webhooks/sanity'
      preLoaderRoute: typeof ApiWebhooksSanityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/cloudinary': {
      id: '/api/webhooks/cloudinary'
      path: '/api/webhooks/cloudinary'
      fullPath: '/api/webhooks/cloudinary'
      preLoaderRoute: typeof ApiWebhooksCloudinaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reconcile/content': {
      id: '/api/reconcile/content'
      path: '/api/reconcile/content'
      fullPath: '/api/reconcile/content'
      preLoaderRoute: typeof ApiReconcileContentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  PhotosSlugRoute: PhotosSlugRoute,
  ApiReconcileContentRoute: ApiReconcileContentRoute,
  ApiWebhooksCloudinaryRoute: ApiWebhooksCloudinaryRoute,
  ApiWebhooksSanityRoute: ApiWebhooksSanityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
